sudo: required
language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - yarn start lint
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then yarn start test.sauce; fi
  - yarn start test
after_success:
  - yarn start report-coverage
  - yarn start semantic-release
notifications:
  email: change
