sudo: required
language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - yarn start lint
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then yarn start test.sauce; fi
  - yarn start test
after_success:
  - yarn start report-coverage
  - yarn start semantic-release
notifications:
  email: change
addons:
  jwt:
    secure: TYracC5vhOH2FHH7vq01iEc7ARG8zI7cqDO4sbex4IlEVeGL14GMGdEd4phkQKPrPmuCAJu43Nw4PfDj3rhPgpCSaTys2Oznuh3QjuipASF9MkaYbks0MnutGAf6QNlBE7gKY7I95pRc7NJaNZyh/vvjO2kYCzb5vfO2jbyC4VsDJz/QKKA8cU6BBlErBm70afTJz/X+a3aoqA0nHX2mDWUMlijrW4dR4e/rp5/2kdj0Jlvt3u/m9YBbLmWqRszdf2EKJ39OG2EtQTt0p5oTgeXJlRS435Yi2HjZJFffebwlPzjk47K39dxUp3cAmvtCtFfCx1CjKcw2isQ89n6YJ4Vi5EIHiXI5gxYqpoX+znQM+QYIK0DQZ6t3exdMb3/s3T8POtrENbL2iVsBDdzb80D3scKtd2V6aPnfep6lJyFje/4t7RJgl67d71+XBesMHfGXCMxrYbaC1HpUbuehT1HmBmaLhug51cR/jk+ebOqcJrcmSwZVJnscMopyliV7slR8XUtSXA8zpx8NNkjhnpnmh4AqxZ2QO32K9GpebuqVYJhvonsdxc4JDslAkKXPDUW0i3hMgO1Mz4UV5O1WEB3HOohHqTezfJXCx/pc91nUthuSUnVp4gLpQZNFdQ3R3tdf0vzRsLW9X4mCU8qSO/MOb/Px69fJqoDMTm2RuLk=
